Bosque = Local{ 
          nomeLocal = "Bosque",
          inventarioLocal = listaParaInventario [madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, madeira, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, comida, rebimbocaDaParafuseta],
          eventosInvestigacao = [EventoInvestigacao {
                                      -- Evento de sucesso
                                requisitosInvestigacao = [machado, lanterna, bussola],
                                alvoInvestigacao = [rebimbocaDaParafuseta],
                                mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                                mensagemSucesso = "Voce esta preparado agora. Sua mao se fecha ao redor do machado, as juntas brancas com o esforço, unhas ferindo sua propria carne. Voce encara o feixe de luz da lanterna, e encara ate deixar de tremer, ate os nervos se calarem. Você esta pronto. Voce adentra a floresta. O vento frio arrepia sua nuca, mas voce segue em frente. Os sons da solidao ecoam nessa terra sem sol, mas voce segue em frente. A paranoia cresce, e o que antes eram esquilos e micos se tornam lobos e raposas e... algo pior. Você anda, segurando um grito na garganta. As sombras dançam ao seu redor, uma valsa lenta e tortuosa com seus maiores medos, o medo de falha, o medo do desconhecido, o medo de que esse bosque será seu lugar final, largado pela natureza, com sua vida a centenas de quilometros de distancia. Mas você persiste, pois ha algo no fim deste caminho, a sua espera. Tao perto que da para sentir. Sentir o cheiro de vitoria. Sentir... uma respiracao, profunda e animalesca, de um predador. Antes de entender o que esta acontecendo, voce vira com o machado em mao, uma volta rapida e violenta. Seu ataque desesperado atinge uma massa de pelos, negros como obsidiana. Um uivo animalesco corta o ceu, mas a unica coisa que voce escuta eh o grito de seus nervos: CORRA. Sem olhar para tras, sem parar, o corpo age antes da mente, a eletricidade e adrenalina lhe jogando mundo adentro, entre arvores, entre galhos que cortam seu rosto e gritos que ferem sua alma. Ja nao da para ignorar o barulho de seu perseguidor, derrubando troncos com força brutal, com o grunido de uma fera insandecida. Nao olhe para tras, nao olhe para tras, NAO OLHE PARA TRAS! A curiosidade vence, como sempre. So uma espiada, apenas o suficiente para ver as garras cortando seus cilios e o mundo virar de cabeça para baixo, suas costas atingirem o chao e seu corpo rolar clareira abaixo. Quando voce recupera seus sentidos, o monstro nao esta mais la. Voce esta sozinho, encarando o ceu, cambaleando ate... aquilo eh uma cabana? O sangue volta para seu rosto e, em desespero, voce quebra a porta com o machado. A cabana esta abandonada, por decadas muito provavelmente, mas, em um armario solitario, voce ve algo: [ITEM DE CARRO]. Você volta pela floresta, seguindo ate o carro, renascido com o fato de estar um passo mais perto de sair daqui."
                                      
                } ,
            EventoInvestigacao {
                                  -- Evento de 2 itens sucesso
                            requisitosInvestigacao = [machado, lanterna],
                            alvoInvestigacao = [rebimbocaDaParafuseta],
                            mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, mas sua lantera sera seu guia para desafios ainda inexplorados. Cada passo lhe deixa mais distante do carro, da seguranca, de onde tudo isso comecou. E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, mas voce estah armado, segurando o machado com tanta forcca que as juntas se tornam brancas. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."                
                } ,
            EventoInvestigacao {
                                  -- Evento de 2 itens sucesso
                            requisitosInvestigacao = [machado, bussola],
                            alvoInvestigacao = [rebimbocaDaParafuseta],
                            mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, com a bussola mostrando o caminho. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso comeccou. E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, mas voce estah armado, segurando o machado com tanta forcca que as juntas se tornam brancas. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."                
                } ,
            EventoInvestigacao {
                                  -- Evento de 2 itens sucesso
                            requisitosInvestigacao = [lanterna, bussola],
                            alvoInvestigacao = [rebimbocaDaParafuseta],
                            mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, com a bussola mostrando o caminho. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, mas sua lantera sera seu guia para desafios ainda inexplorados. Cada passo lhe deixa mais distante do carro, da seguranca, de onde tudo isso comecou. E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, lhe lembram o quao desarmado voce realmente eh. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."                
                } ,
            EventoInvestigacao {
                               -- Evento de 1 item sucesso
                         requisitosInvestigacao = [machado],
                         alvoInvestigacao = [rebimbocaDaParafuseta],
                         mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, mas voce estah armado, segurando o machado com tanta forcca que as juntas se tornam brancas.. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."               
                } ,
            EventoInvestigacao {
                               -- Evento de 1 item sucesso
                         requisitosInvestigacao = [bussola],
                         alvoInvestigacao = [rebimbocaDaParafuseta],
                         mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, com a bussola mostrando o caminho. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, mas voce estah armado, segurando o machado com tanta forcca que as juntas se tornam brancas. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."               
                } ,

            EventoInvestigacao {
                               -- Evento de 1 item sucesso
                         requisitosInvestigacao = [lanterna],
                         alvoInvestigacao = [rebimbocaDaParafuseta],
                         mensagemFalha = "Você adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca, até os sons da solidão, longe de tudo, longe de todos, apenas sua mente e a natureza. As árvores são altas e grossas, desafiando os cés e cortando o sol, cada passo lhe deixando mais distante da luz, do carro, de onde tudo isso começou. E os sons.... Os sons lhe enchem a mente, lhe ensinam o que é ter medo, lhe lembram do quão desarmado você realmente é. Há algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio não para o suor que desce pela testa, gelado como metal. VocÊ dá mais alguns passos. Você está de volta no carro, de volta na luz. Na próxima vez, você irá preparado.",
                            mensagemSucesso = "Voce adentra a floresta, sentindo-a como se fosse a primeira vez. Cada detalhe penetra sua pele, desde o vento frio arrepiando a nuca ate os sons da solidao, longe de tudo, longe de todos, apenas sua mente e a natureza. As arvores sao altas e grossas, desafiando os ceus e cortando o sol, mas sua lantera sera seu guia para desafios ainda inexplorados. Cada passo lhe deixa mais distante do carro, da seguranca, de onde tudo isso comecou. E os sons.... sons lhe enches a mente, lhe ensinam o que eh ter medo, mas voce estah armado, segurando o machado com tanta forcca que as juntas se tornam brancas. Hah algo nesta floresta. Algo antigo e sombrio, algo inumano na espreita. O vento frio nao para o suor que desce pela testa, gelado como metal. Voce dah mais alguns passos. Voce esta de volta no carro, de volta no familiar. Na proxima vez, voce irah preparado."               
                }] ,
        eventosColeta = 
            [EventoColeta {
                    requisitosColeta = [],
                    coletado = madeira 
                },
                EventoColeta {
                    requisitosColeta = [],
                    coletado = madeira 
                },
                EventoColeta {
                    requisitosColeta = [],
                    coletado = madeira 
                } ] }
                   



                   --Você sente a presença se impor sobre você, um conjunto disforme de pelo e garras e músculos e sangue, o peito subindo e descendo com a respiração ofegante de um predador que alcançou sua presa, segura em garantir o jantar. Você é não mais. A respiração dá lugar a um grunhido, e o grunhido para um rosnar. A criatura está sobre você. O que se segue é o eco de ossos quebrando, esmagados como galhos secos, o som molhado da carne dilacerada, o calor do sangue derramado. Não há tempo para gritar. Não há tempo para piscar. Sua vida não passa diante dos seus olhos. Suas preces nunca alcançarão seu Deus. Não há ninguém para receber suas últimas palavras. Você encara os olhos vermelhos do monstro uma última vez, antes tudo ficar escuro.